version: '3.4'

services:
  weather-api:
    image: weather-api 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - weather-db
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  weather-db:
    container_name: weather-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - weather_data:/var/lib/postgresql/data/

volumes:
  weather_data: